[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[features]
derive = []

[dependencies]
wgpu = "30.0.0"
bytemuck = { version = "1", features = ["derive"] }
image    = { version = "0.25", default-features = false, features = ["png"] }
glam = { version = "0.33.2", features = ["bytemuck"] }
kira     = "0.9"
log      = "0.4"
winit    = "0.30"
pollster = "0.3"
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.19"
derive-new = "0.7.0"
derive_more = { version = "2.1.1", features = ["full"] }
proc-macros = { version = "0.1.0", path = "../proc-macros" }
